### ISSUE TITLE
Crash when using Unicode Character

### ISSUE THREAD

**Issue by zeng-y-l** [pest-parser/pest-ide-tools#21]
Using Unicode characters, such as Chinese, may crashes. But sometimes I can't reproduce it.

Source:

```
foobar = { "中文" }
```

Log:

```
thread 'main' panicked at 'byte index 13 is not a char boundary; it is inside '中' (bytes 12..15) of `foobar = { "中文" }`', C:\Users\zeng-\.cargo\registry\src\mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd\pest-language-server-0.2.1\src\helpers.rs:117:20
```

**Comment by Jamalam360** [comment]
I can't reproduce this :/ but I can see why it should be a problem. Maybe we should use [this crate](https://docs.rs/unicode-segmentation/latest/unicode_segmentation/struct.Graphemes.html) instead of the `chars` method?

If anyone can figure out a reliable reproduction that would be much appreciated

**Comment by Jamalam360** [comment]
I can't reproduce this :/ but I can see why it should be a problem. Maybe we should use [this crate](https://docs.rs/unicode-segmentation/latest/unicode_segmentation/struct.Graphemes.html) instead of the `chars` method?

If anyone can figure out a reliable reproduction that would be much appreciated

**Comment by zeng-y-l** [comment]
Maybe I can reproduce the problem now. I use Windows 11, VSCode 1.77.3.

Make the mouse move over `中文`, like this

![a](https://user-images.githubusercontent.com/89503645/233582331-9a4d83a5-2053-456a-88a9-7f2777fcfc52.gif)

**Comment by Jamalam360** [comment]
Yes, that reproduction works for me. I'll try some things out, thank you

**Comment by Jamalam360** [comment]
This has been fixed using the unicode segmentation crate, from my testing. Thank you for the report - the release will be coming out shortly.
